# Generated by Django 5.0.6 on 2024-05-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_bill_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
