# Generated by Django 5.0.6 on 2024-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_remove_bill_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
