# Generated by Django 5.0.6 on 2024-05-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_bill_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
