# Generated by Django 5.0.6 on 2024-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_billitem_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
