# Generated by Django 5.0.6 on 2024-05-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_billitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='subtotal',
        ),
    ]
