# Generated by Django 5.0.6 on 2024-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_billitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
